### ISSUE TITLE
Access for publishing

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/aws-es-client#5]
@Holger-Will for the auto publish the current action is not working because I am not collaborator for this package on `npm` (so my token doesn't have publish rights for it)

You can either:
- add me as collaborator
- generate a token on your side and replace the secret `NPM_TOKEN` on this repo and that should do the trick

When you did it just ping me so I can give it a shot again and see if it works! :+1:

**Comment by Holger-Will** [comment]
@alexlemaire ping

**Comment by alexlemaire** [comment]
Publish is working fine now, thanks! Closing now :+1:
